android: refactor select_android_device

diff --git a/zsh/custom/android/select_android_device b/zsh/custom/android/select_android_device
--- a/zsh/custom/android/select_android_device
+++ b/zsh/custom/android/select_android_device
@@ -3,63 +3,19 @@
 : ${FASTBOOT_BIN:=$(whence -p fastboot)}
 : ${ADB_BIN:=$(whence -p adb)}
 
-function paddedstr()
-{
-  local len=$1
-  shift
-  local str=$*
-
-  local npadding=$(expr $len - ${#str})
-  local padding
-  [ $npadding -gt 0 ] && padding=$(printf '%*s' $npadding ' ') || padding=
-  echo "${str}${padding}"
-}
-
-function print_android_info()
-{
-  local pretty=$1
-  local aserial=$2
-  local dev=$3
-  local rev=$4
-  local build=$5
-  local devrev
-
-  [ -n "$rev" -a "$rev" != "0" ] && devrev="${dev# } (${rev# })" || devrev=${dev}
-  if $pretty; then
-    echo -n "$(paddedstr 16 $aserial) | "
-    [ -z "$build" ] && build="N/A"
-    echo -n "$(paddedstr 16 $build) | "
-    echo "$(paddedstr 22 $devrev)"
-  else
-    echo -n ${devrev}
-    [ -n "$build" ] && echo -n ":${build# }"
-    echo ":${aserial}"
-  fi
-}
+declare -a ANDROID_DEVICES_COLUMNS=(serial devrev build protocol)
+declare -A ANDROID_DEVICES_HEADERS=(
+  [serial]=" Serial No"
+  [devrev]=" Device (Revision)"
+  [build]="  Android Build"
+  [protocol]="  Mode "
+)
 
 function get_android_adb_var()
 {
   local aserial=$1
   local varname=$2
   echo -n $($ADB_BIN -s $aserial shell getprop $varname)
-}
-
-function get_android_adb_info()
-{
-  local aserial=$1
-  local pretty=${2:-false}
-  [ "$aserial" = "" ] && return 1
-
-  local state=$($ADB_BIN -s $aserial get-state 2>/dev/null)
-  [ "$state" != "device" ] && return 1
-
-  local build=$(get_android_adb_var $aserial ro.build.id)
-  local dev=$(get_android_adb_var $aserial ro.hardware)
-  local rev=$(get_android_adb_var $aserial ro.revision)
-
-  print_android_info $pretty "$aserial" "$dev" "$rev" "$build"
-
-  return 0
 }
 
 function get_android_fb_var()
@@ -72,53 +28,108 @@ function get_android_fb_var()
   [ -n "$val" -a "$val" != "unknown variable" ] && [[ "$val" =~ ^[[:alnum:]].* ]] && echo $val
 }
 
+function get_android_adb_info()
+{
+  local aserial=${1:-$ANDROID_SERIAL}
+  [ "$aserial" = "" ] && return 1
+
+  local state=$($ADB_BIN -s $aserial get-state 2>/dev/null)
+  [ "$state" != "device" ] && return 1
+
+  declare -A devinfo=(
+    [serial]="$aserial"
+    [dev]="$(get_android_adb_var $aserial ro.hardware)"
+    [rev]="$(get_android_adb_var $aserial ro.revision)"
+    [build]="$(get_android_adb_var $aserial ro.build.id)"
+    [protocol]="adb"
+  )
+  declare -p devinfo
+}
+
 function get_android_fb_info()
 {
-  local aserial=$1
-  local pretty=${2:-false}
+  local aserial=${1:-$ANDROID_SERIAL}
   [ "$aserial" = "" ] && return 1
 
   local fb_connected=$($FASTBOOT_BIN devices | grep ^$aserial)
-  if [ -n "$fb_connected" ]; then
-    local dev=$(get_android_fb_var $aserial product)
-    # if no output found now, it's likely going to fail for next ones too
-    [ -n "$dev" ] || return 1
-    local rev=$(get_android_fb_var $aserial hw-revision)
-    local build=$(get_android_fb_var $aserial version-bootloader)
+  [ -n "$fb_connected" ] || return 1
+  local dev=$(get_android_fb_var $aserial product)
+  # if no output found now, it's likely going to fail for next ones too
+  [ -n "$dev" ] || return 1
 
-    print_android_info $pretty "$aserial" "$dev" "$rev" "$build"
+  declare -A devinfo=(
+    [serial]=$aserial
+    [dev]=$dev
+    [rev]=$(get_android_fb_var $aserial hw-revision)
+    [build]=$(get_android_fb_var $aserial version-bootloader)
+    [protocol]=fastboot
+  )
+  declare -p devinfo
+}
 
-    return 0
+function print_row()
+{
+  eval "declare -A devinfo=${1#*=}"
+  [ -z "${devinfo[devrev]}" ] && devinfo[devrev]="${devinfo[dev]} (${devinfo[rev]})"
+
+  declare -a fields=()
+  for k in "${(@k)ANDROID_DEVICES_COLUMNS}"; do
+    fields+=${devinfo[$k]:-"N/A"}
+  done
+  echo ${(j:\t| :)fields}
+}
+
+function print_header()
+{
+  declare -A sep
+  for k in "${(@k)ANDROID_DEVICES_COLUMNS}"; do
+    local len=$(((${#ANDROID_DEVICES_HEADERS[$k]}+1)/2))
+    sep[$k]=$(printf " -"%.0s {1..$len})
+  done
+  print_row "$(declare -p ANDROID_DEVICES_HEADERS)"
+  print_row "$(declare -p sep)"
+}
+
+function list_android_devices_helper()
+{
+  while getopts 'h' arg; do
+    case $arg in
+      h) print_header ;;
+    esac
+  done
+  shift $((OPTIND-1))
+
+  if command adb start-server; then
+    local adb_devices=$(command adb devices -l | sed -n "2,100p")
+    for dev in ${(f)adb_devices}; do
+      local aserial=${dev%% *}
+      print_row "$(get_android_adb_info $aserial)"
+    done
   fi
 
-  return 1
+  local fb_devices=$(command fastboot devices -l)
+  for dev in ${(f)fb_devices}; do
+    local aserial=${dev%% *}
+    print_row "$(get_android_fb_info $aserial)"
+  done
 }
 
 function list_android_devices()
 {
-  declare -a devices
+  list_android_devices_helper $@ | column -t -s $'\t'
+}
 
-  command adb start-server || ( echo "Unable to start adb"; return 1 )
+function show_android_device()
+{
+  local aserial=${1:-$ANDROID_SERIAL}
+  local info=$(get_android_adb_info $ANDROID_SERIAL || get_android_fb_info $ANDROID_SERIAL)
+  eval "declare -A devinfo=${info#*=}"
 
-  local adb_devices=$(command adb devices -l | sed -n "2,100p")
-  local fb_devices=$(command fastboot devices -l)
-  for dev in ${(f)adb_devices} ${(f)fb_devices}; do
-    local aserial=${dev%% *}
-    local devinfo=
-    local mode=
-    if [[ $dev == *"fastboot"* ]]; then
-      mode=fastboot
-      devinfo=$(get_android_fb_info $aserial true)
-    else
-      mode=adb
-      devinfo=$(get_android_adb_info $aserial true)
-    fi
-    if [ -n "$devinfo" ]; then
-      echo "$devinfo $mode"
-    else
-      echo "$dev"
-    fi
-  done
+  [ -n "$devinfo" ] || return 1
+
+  echo -n "${devinfo[dev]} (${devinfo[rev]})"
+  [ -n "${devinfo[build]}" ] && echo -n ":${devinfo[build]# }"
+  echo ":${aserial}"
 }
 
 function select_android_device_fzf()
@@ -157,8 +168,8 @@ function select_android_device_fzf()
   fi
 
   export ANDROID_SERIAL=${aserial}
-  local devinfo=$(get_android_adb_info $ANDROID_SERIAL || get_android_fb_info $ANDROID_SERIAL || echo "$ANDROID_SERIAL")
-  echo "Selected device: $devinfo"
+  echo -n "Selected device: "
+  show_android_device
 }
 
 function select_android_device_list()
@@ -194,10 +205,8 @@ function select_android_device_list()
   fi
 
   export ANDROID_SERIAL=${serial_list[$selection]}
-  local devinfo=$(get_android_adb_info $ANDROID_SERIAL || get_android_fb_info $ANDROID_SERIAL || echo "$ANDROID_SERIAL")
-  echo "Selected device #${selection}: $devinfo"
-
-  return 0
+  echo -n "Selected device #${selection}: "
+  show_android_device
 }
 
 function usage()
@@ -207,20 +216,27 @@ function usage()
 If provided will try to find a device that matches closely DEVICE argument
 
 Options:
+  -a      Use list and prompt for device selection instead of fzf
+  -f      Force use of fzf for device selection
   -l      List Android devices connected and exit
   -h      Print this help"
 }
 
-while getopts 'lh?' arg; do
+pref="auto"
+while getopts 'aflhp?' arg; do
   case $arg in
-    l) list_android_devices; return 0 ;;
+    a) pref="list" ;;
+    f) pref="fzf" ;;
+    l) list_android_devices -h; return 0 ;;
+    p) show_android_device; return 0 ;;
     h|?) usage; return 0; ;;
   esac
 done
+shift $((OPTIND-1))
 
-if [ -n "$(command -v fzf)" ]; then
+if [ "$pref" != "list" -a -n "$(command -v fzf)" ]; then
   select_android_device_fzf $@
-else
+elif [ "$pref" != "fzf" ]; then
   select_android_device_list $@
 fi
 
